spring.application.name=gitdemo
spring.datasource.url=jdbc:mysql://localhost:3306/gitpractice
spring.datasource.username=root
spring.datasource.password=Ammi@456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true