pipeline {

    agent any

    tools {
        jdk 'JDK21'
        maven 'Maven3'
    }

    stages {
    stage('Clean Workspace') {
        steps {
            cleanWs()
        }
    }

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                dir('gitdemo') {
                    bat 'mvn clean package'
                }
            }
        }

        stage('Archive Artifact') {
            steps {
                archiveArtifacts artifacts: 'gitdemo/target/*.jar', fingerprint: true
            }
        }

        stage('Publish JUnit Reports') {
            steps {
                junit 'gitdemo/target/surefire-reports/*.xml'
            }
        }

    }

}