pipeline {

    agent any

    tools {
        jdk 'JDK21'
        maven 'Maven3'
    }

    stages {

        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                dir('gitdemo') {
                    bat 'mvn clean verify'
                }
            }
        }

        stage('SonarQube Scan') {
            steps {
                dir('gitdemo') {
                    withSonarQubeEnv('SonarQube') {
                        bat '''
                        mvn sonar:sonar ^
                        -Dsonar.projectKey=gitdemo ^
                        -Dsonar.host.url=http://localhost:9000
                        '''
                    }
                }
            }
        }

//         stage('Quality Gate') {
//             steps {
//                 timeout(time: 5, unit: 'MINUTES') {
//                     waitForQualityGate abortPipeline: true
//                 }
//             }
//         }
stage('Check Docker') {
    steps {
        bat 'docker --version'
        bat 'docker ps'
    }
}
stage('Build Docker Image') {
    steps {
        dir('gitdemo') {
            bat 'docker build -t gitdemo .'
        }
    }
}

        stage('Archive Artifact') {
            steps {
                archiveArtifacts artifacts: 'gitdemo/target/*.jar', fingerprint: true
            }
        }

        stage('Publish JUnit Reports') {
            steps {
                junit 'gitdemo/target/surefire-reports/*.xml'
            }
        }

    }

}